from typing import List, Optional

from pydantic import BaseModel, Field, field_validator


class RecommendationRequest(BaseModel):
    """
    Input from the client to request restaurant recommendations.
    """

    location: Optional[str] = Field(None, description="City or area, e.g. 'Bangalore'. If omitted, no location filter applies.")
    price_range: str = Field(
        ...,
        description="Price band: 'low', 'mid', or 'high'",
        pattern="^(low|mid|high)$",
    )
    min_rating: float = Field(
        0.0,
        ge=0.0,
        le=5.0,
        description="Minimum acceptable rating on a 0–5 scale.",
    )
    cuisine: Optional[str] = Field(
        None,
        description="Preferred cuisine, e.g. 'Italian'. If omitted, no cuisine filter is applied.",
    )
    user_id: Optional[str] = Field(
        None,
        description="Optional user identifier used for personalization.",
    )

    @field_validator("location")
    def normalize_location(cls, value: Optional[str]) -> Optional[str]:  # noqa: D417
        if value is None:
            return value
        cleaned = value.strip()
        return cleaned if cleaned else None

    @field_validator("cuisine")
    def normalize_cuisine(cls, value: Optional[str]) -> Optional[str]:  # noqa: D417
        if value is None:
            return value
        cleaned = value.strip()
        return cleaned if cleaned else None


class RestaurantOut(BaseModel):
    """
    Restaurant representation returned to the client.
    """

    name: str
    location: str
    rating: float
    price: float
    cuisine: str
    reason: str


class RecommendationResponse(BaseModel):
    """
    Wrapper for the recommendations list.
    """

    results: List[RestaurantOut]
    llm_summary: Optional[str] = Field(
        default=None,
        description="Optional natural-language summary generated by Groq LLM.",
    )
    llm_used: bool = Field(
        default=False,
        description="True if Groq LLM was called to enhance the recommendations.",
    )


class FeedbackRequest(BaseModel):
    """
    Input for the feedback endpoint.
    """

    user_id: str = Field(..., description="User identifier.")
    restaurant_name: str = Field(..., description="Name of the restaurant the feedback refers to.")
    liked: bool = Field(..., description="True if the user liked the restaurant, False otherwise.")

